import { Component, OnInit } from '@angular/core';
import { ChartType, ChartOptions } from 'chart.js';
import Swal from 'sweetalert2';
import {
  Label,
  monkeyPatchChartJsLegend,
  monkeyPatchChartJsTooltip,
  SingleDataSet,
} from 'ng2-charts';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { map, shareReplay } from 'rxjs/operators';
import * as Chart from 'chart.js';
import { title } from 'process';
import { Router } from '@angular/router';
import { ReportingService } from 'src/app/Report/Report resources/reporting.service';
import { AdminService } from '../admin resources/admin.service';
import { NgxChartsModule } from '@swimlane/ngx-charts';
import { DatePipe } from '@angular/common';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  providers: [DatePipe]
})
export class HomeComponent implements OnInit {
  date:any;
  //variables
  numOfStudents:any;
  numOfTutors: any;
  numOfUniversities:any;
  numOfModules:any;
  numOfDegrees:any;
  StudentUniData: any[] = [];
  CourseData: any[] = [];
  sentance:string="";

  //functions
  TotalStudents(){
    this.adminService.getTotalStudents().subscribe((result) => {
      this.numOfStudents = result;
      console.log(this.numOfStudents);
    })
  }

  TotalTutors(){
    this.adminService.getTotalTutors().subscribe((result) => {
      this.numOfTutors = result;
      console.log(this.numOfTutors);
    })
  }

  
  TotalUniversities(){
    this.adminService.getTotalUniversities().subscribe((result) => {
      this.numOfUniversities = result;
      console.log(this.numOfUniversities);
    })
  }

  TotalDegrees(){
    this.adminService.getTotalDegrees().subscribe((result) => {
      this.numOfDegrees = result;
      console.log(this.numOfDegrees);
    })
  }

  TotalModules(){
    this.adminService.getTotalModules().subscribe((result) => {
      this.numOfModules = result;
      console.log(this.numOfModules);
    })
  }

  StudentUniGraph(){
    this.adminService.getStudentUniGraphData().subscribe((result) => {
      this.StudentUniData = result;
      console.log(this.StudentUniData);
    })
  }

  CoursePieGraphData(){
    this.adminService.getCoursePieGraphData().subscribe((result) => {
      this.CourseData = result;
      console.log(this.CourseData);
    })
  }

    //Student Uni Bar chart options
    showXAxis = true;
    showYAxis = true;
    
    gradient = false;
    showLegend = true;
    showXAxisLabel = true;
    xAxisLabel = 'University Name';
    showYAxisLabel = true;
    yAxisLabel = 'Number of students';
  
    colorScheme = {
      domain: ['#096E94', '#3CC0F2', '#606664', '#0F926A', '#834111']
    };
  
   

  // CourseCHart options
  
  gradient1: boolean = true;
  showLegend1: boolean = true;
  showLabels: boolean = true;
  isDoughnut: boolean = true;
  legendPosition: string = 'right';

  colorScheme1 = {
    domain: ['#7E3D27', '#7A7E27', '#277E5A', '#53277E','#7E273C','#50277E']
  };


  public DownloadUniPDF():void {
    this.date=new Date();
 let latest_date =this.datePipe.transform(this.date, 'dd-MM-yyyy');
this.sentance = "Date generated:"+latest_date;
document.getElementById('StudentOfUniData').style.width = '1000px'
    let data = document.getElementById('StudentOfUniData');
   
      
    html2canvas(data).then(canvas => {
        
        let fileWidth = 400;
        let fileHeight = canvas.height * fileWidth / canvas.width;
        var img = new Image();
  var src = "../.././assets/pics/HD logo.png";
  img.src = src;


        const FILEURI = canvas.toDataURL('image/png')
        let PDF = new jsPDF('l', 'mm', 'a4');
        let position = 0;
        PDF.addImage(img, 'PNG', 10, 5, 25, 25)
        PDF.addImage(FILEURI, 'PNG', 45, 70, fileWidth, fileHeight)
        PDF.setFontSize(22);
        PDF.setFont(undefined, 'bold')
        PDF.text("Number of students at each university report",70,20);
        PDF.setFontSize(9);
        PDF.setFont(undefined, 'normal')
        PDF.text("Description: Graph shows the number of students at each university.",10,45);
        PDF.text("Generated by: Admin.",10,50);
        PDF.text(this.sentance,10,55);
        
        ;
      
        PDF.save('StudentsOfUniversities.pdf');
        document.getElementById('StudentOfUniData').style.width = '450px'
    });     

    
  }


 

  public DownloadCoursePDF():void {
    var imgs = new Image();
  var src = "../.././assets/pics/HD logo.png";
  imgs.src = src;
    let data = document.getElementById('CourseData');
    document.getElementById('CourseData').style.width = '1000px'
    this.date=new Date();
    let latest_date =this.datePipe.transform(this.date, 'dd-MM-yyyy');
   this.sentance = "Date generated:"+latest_date;
    html2canvas(data).then(canvas => {
        
        let fileWidth = 400;
        let fileHeight = canvas.height * fileWidth / canvas.width;
        
        const FILEURI = canvas.toDataURL('image/png')
        let PDF = new jsPDF('l', 'mm', 'a4');
        let position = 0;
        PDF.addImage(imgs, 'PNG', 10, 5, 25, 25)
        PDF.addImage(FILEURI, 'PNG', 60, 50, fileWidth, fileHeight)
        PDF.setFontSize(22);
        PDF.setFont(undefined, 'bold')
        PDF.text("Difference in sales between short courses report",58,20);
        PDF.setFontSize(9);
        PDF.setFont(undefined, 'normal')
        PDF.text("Description: Graph shows the total amount that a course has been sold in comparison to other courses.",10,45);
        PDF.text("Generated by: Admin.",10,50);
        PDF.text(this.sentance,10,55);
        
        PDF.save('StudentsOfUniversities.pdf');
        document.getElementById('CourseData').style.width = '510px'
        
    });     

    
  }

  x(){
    Swal.fire(
      '',
      'Successfully downloaded report',
      'success'
    )
  }

  isHandset$: Observable<boolean> = this.breakpointObserver
    .observe(Breakpoints.Handset)
    .pipe(
      map((result) => result.matches),
      shareReplay()
    );

  

  constructor(
    private breakpointObserver: BreakpointObserver,
    private route: Router,
    private adminService : AdminService, private datePipe: DatePipe
  ) {
    monkeyPatchChartJsTooltip();
    monkeyPatchChartJsLegend();
   
  }

  ngOnInit(): void {
    this.TotalStudents();
    this.TotalTutors();
    this.TotalUniversities();
    this.TotalModules();
    this.TotalDegrees();
    this.StudentUniGraph();
    this.CoursePieGraphData();
    
  }

  public logout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('id');
    this.route.navigate(['/loginhomepage/login']);
  };
  //   Swal.fire({

  //     icon: 'warning',
  //     title: 'Are you sure you want to logout',
  //     confirmButtonText: 'Confirm',

  //     showCancelButton: true,
  //     confirmButtonColor: '#3085d6',
  //     cancelButtonColor: '#d33',
  //     cancelButtonText: 'Cancel'

  //   })
  // }

  axisFormat(val) {
    if (val % 1 === 0) {
      return val.toLocaleString();
    } else {
      return '';
    }
  }
}
