import { Component, OnInit } from '@angular/core';
import Swal from 'sweetalert2';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Router } from '@angular/router';
import { ReportingService } from '../../Report resources/reporting.service';
import { NgxPaginationModule } from 'ngx-pagination';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-total-students-report',
  templateUrl: './total-students-report.component.html',
  styleUrls: ['./total-students-report.component.scss']
})
export class TotalStudentsReportComponent implements OnInit {
  date:any;
  sentance:string="";
  totalLength:any;
  page:number = 1;
  studentList:any= [];

  constructor(  
    private reportService: ReportingService,
    private router: Router,private datePipe: DatePipe ) { }

  ngOnInit(){
    this.getStudentDetails();
  }
  x(){
    Swal.fire(
      '',
      'Successfully downloaded report',
      'success'
    )
  }

  public logout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('id');
    this.router.navigate(['/loginhomepage/login']);
  };

  getStudentDetails() {
    
    this.reportService.getTotalStudents().subscribe((result) => {
      this.studentList = result; 
      this.totalLength = this.studentList.length;
      console.log(this.studentList);
    });
  }



  public DownloadPDF():void {
    let data = document.getElementById('TutorDetailsData');
    var imgs = new Image();
    var src = "../.././assets/pics/HD logo.png";
    imgs.src = src;
    this.date=new Date();
    let latest_date =this.datePipe.transform(this.date, 'dd-MM-yyyy');
   this.sentance = "Date generated:"+latest_date;
    html2canvas(data).then(canvas => {
        
        let fileWidth = 180;
        let fileHeight = canvas.height * fileWidth / canvas.width;
        
        const FILEURI = canvas.toDataURL('image/png')
        let PDF = new jsPDF('p', 'mm', 'a4');
        PDF.addImage(imgs, 'PNG', 10, 5, 25, 25)
        let position = 0;
        PDF.addImage(FILEURI, 'PNG', 15, 60, fileWidth, fileHeight)
        PDF.setFontSize(22);
        PDF.setFont(undefined, 'bold')
        PDF.text("Student details report",70,20);
        PDF.setFontSize(9);
        PDF.setFont(undefined, 'normal')
        PDF.text("Description: Table displays list of all registered students and their details.",15,40);
        PDF.text("Generated by: Admin.",15,45);
        PDF.text(this.sentance,15,50);
        PDF.save('TotalStudentsReport.pdf');
    });     
  }

  public RedirectReportHome(){
    this.router.navigateByUrl('/report-home');
  }








}
